version: 2

nodejs: &nodejs
  docker:
    - image: circleci/node:8.11
  working_directory: /tmp/workspace/nodejs

jobs:
  build:
    <<: *nodejs
    steps:
      - checkout
      - run:
          name: npm install --production
          command: npm install --production
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - index.js
            - package.json
            - lib

  test:
    <<: *nodejs
    steps:
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm test
          command: npm test 
  deploy:
    <<: *nodejs
    steps:
      - run:
          name: npm test
          command: npm test 
workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires: 
            - build
      - deploy:
          context: org-global
          requires: 
            - test
          filters: 
            branches: 
              only: circle2
